apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: productpage
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: kimikowang/productpage:knative_0.1
            ports: 
            - containerPort: 9080
              name: http1
              protocol: TCP
            env:
            - name: VERSION
              value: v1
            - name: DETAILS_HOSTNAME
              value: details.default.svc.cluster.local
            - name: RATINGS_HOSTNAME
              value: ratings.default.svc.cluster.local
            - name: REVIEWS_HOSTNAME
              value: reviews.default.svc.cluster.local
            - name: DETAILS_SERVER_PORT
              value: "80"
            - name: RATINGS_SERVER_PORT
              value: "80"
            - name: REVIEWS_SERVER_PORT
              value: "80"