apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: reviews
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: iter8/reviews-v1:knative_0.1
            ports: 
            - containerPort: 9080
              name: http1
            env:
            - name: VERSION
              value: v1
            - name: RATINGS_HOSTNAME
              value: ratings.default.svc.cluster.local
            - name: RATINGS_SERVER_PORT
              value: "80"
