sudo: required

dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
env:
  - ITER8_ANALYTICS_METRICS_BACKEND_URL="http://localhost:9090"

before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.16.7/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  - sudo minikube start --vm-driver=none --kubernetes-version=v1.16.7
  - sudo minikube update-context
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
  - git clone https://github.com/iter8-tools/e2e-tests.git

script:
  - ls -l
  - make test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin;
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
        export IMG="iter8/iter8-analytics:$TRAVIS_BUILD_NUMBER-PR_$TRAVIS_PULL_REQUEST";
        echo "Building PR Docker image - $IMG";
        make docker-build;
        make docker-push;
      else
        export IMG="iter8/iter8-analytics:$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT";
        echo "Building Docker image - $IMG";
        make docker-build;
        make docker-push;
        LATEST="iter8/iter8-analytics:latest";
        echo "Tagging image as latest - $LATEST";
        docker tag $IMG $LATEST;
        export IMG=$LATEST;
        make docker-push;
      fi
    fi
